# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.5"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "debian"
  config.vm.boot_timeout = 500
  config.vm.network :public_network

  
  config.vm.provision "shell", path: "../../debian_harden.sh"
  
  
end
