#!/bin/bash

cd info

# when run with --revert, replaces current login.defs with the previous version
if [ $1 = "--revert" ] 
then
   # tests to see if backup file exists
	if [ ! -f login.defs.old] 
	then
		echo "login.defs.old was not found. Aborting..."
	else 			
		# if it does, replace current login defs with old
		sudo cp login.defs.old /etc/login.defs
	fi

# if not run with --revert, replace the login.defs
else
	# save the current login.defs to a backup file, login.defs.old
	sudo cp /etc/login.defs login.defs.old
	
	# copies everything but password fields from login.defs to login.defs.new
	egrep -v '^#|^$|PASS' /etc/login.defs > login.defs.new	

	# appends the appropriate password files to login.defs.new
	echo "PASS_MIN_DAYS   0" >> login.defs.new
	echo "PASS_MAX_DAYS   30" >> login.defs.new
	echo "PASS_WARN_AGE   7" >> login.defs.new

	: ' 
	replaces login.defs.new (with appropriate password fields
	to appropriate login defs folder
	'
	sudo cp login.defs.new /etc/login.defs
fi
