#!/bin/bash

: ' 
This program relies on users.authorized being created, which
means that the auth script must be run first. This program
manages users in the group sudo. If a user should be a member
of sudo with respect to the user-defined file admins,
then add them to the group if they are not already a member.
Otherwise, delete them from the group sudo if they are a member
but should not be.
'

# move into working directory
cd info

echo "# Enter the administrators for the system below," > admins
echo "# One username per line" >> admins
vi admins

echo "\n\n"

# if authorized user should not be admin, delete it from group sudo
# if authorized user should be admin, add to group sudo
while read LINE
do
        if [ -s $(grep -i $LINE admins) ]
        then
                sudo deluser $LINE sudo
        else
                sudo adduser $LINE sudo
        fi
done < users.authorized
