#!/bin/bash

# Enables Ubuntu firewall, installs htop, and updates apt configuration
# for auto updates and periodic checks for updates

cd info

sudo ufw enable

sudo apt install htop --assume-yes

sudo cp update.template /etc/apt/apt.conf.d/10periodic
sudo cp update.template /etc/apt/apt.conf.d/20auto-upgrades

sudo apt-get update
sudo apt-get --assume-yes upgrade
sudo apt-get --assume-yes dist-upgrade

echo "ufw enabled"
echo "htop was installed"
echo "system successfully updated"
