#!/bin/sh

#################################################################################
#
#   hardeningone
# ------------------
#
# Copyleft GPL3 2010-2011, Mauro Risonho de Paula Assumpção (mauro.risonho@gmail.com), 
# Web site: http://
#
# hardeningone comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Kernel
#
#################################################################################
#
    InsertSection "" #34. Kernel Hardening"
#
#################################################################################
#
    # Test        : KRNL-6000
    # Description : Check sysctl parameters
    # Sysctl      : net.ipv4.icmp_ingore_bogus_error_responses (=1)
    if [ ! "${SYSCTL_READKEY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no KRNL-6000 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Check sysctl key pairs in scan profile"
    if [ ${SKIPTEST} -eq 0 ]; then
        Display --indent 2 --text "" # R-TEC-KRNL-6000-Comparando sysctl key pairs com o profile scaneado..."
        FIND=`grep "^sysctl:" ${PROFILE} | sed 's/ /:space:/g'`
        for I in ${FIND}; do
            tFINDkey=`echo ${I} | awk -F: '{ print $2 }'`
            tFINDexpvalue=`echo ${I} | awk -F: '{ print $3 }'`
            tFINDhp=`echo ${I} | awk -F: '{ print $4 }' | grep "[0-9]"`
            tFINDdesc=`echo ${I} | awk -F: '{ print $5 }' | sed 's/:space:/ /g'`
                
            tFINDcurvalue=`${SYSCTL_READKEY} ${tFINDkey} 2> /dev/null`
            if [ ! "${tFINDcurvalue}" = "" ]; then
            
        	if [ "${tFINDexpvalue}" = "${tFINDcurvalue}" ]; then
        	    logtext "R-TEC-KRNL-6000-Resultado: sysctl key ${tFINDkey} contem conteudo atual é igual ao esperado  (${tFINDexpvalue})"
        	    Display --indent 6 --text "" # ${tFINDkey} (${tFINDexpvalue})" --result OK --color GREEN
        	    AddHP ${tFINDhp} ${tFINDhp}
        	  else
        	    logtext "R-TEC-KRNL-6000-Resultado: sysctl key ${tFINDkey} é diferente do valor esperado no scan profile. Esperado=${tFINDexpvalue}, Real=${tFINDcurvalue}"
            	    Display --indent 6 --text "" # ${tFINDkey} (${tFINDexpvalue})" --result DIFERENTE --color RED
            	    AddHP 0 ${tFINDhp}
    		fi  
    	      else
    	        logtext "R-TEC-KRNL-6000-Resultado: key ${tFINDkey} does not exist on this machine"
    	    fi
        done
    fi
#
#################################################################################
#

wait_for_keypress

#
#================================================================================
# hardeningone - Copyleft GPL3 2010-2011, Mauro Risonho de Paula Assumpção -  - 
