#!/bin/sh

#################################################################################
#
#   hardeningone
# ------------------
#
# Copyleft GPL3 2010-2011, Mauro Risonho de Paula Assumpção (mauro.risonho@gmail.com), 
# Web site: http://
#
# hardeningone comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
#################################################################################
#
# Name services
#
#################################################################################
#
    InsertSection "" #9.Software: name services"
#
#################################################################################
#
    BIND_RUNNING=0
    BIND_CONFIG_LOCS="/etc /etc/bind /usr/local/etc"
    BIND_CONFIG_LOCATIONS=""
    POWERDNS_RUNNING=0
    POWERDNS_CONFIG_LOCS="/etc/powerdns /usr/local/etc"
    POWERDNS_CONFIG_LOCATION=""
    YPBIND_RUNNING=0
#
#################################################################################
#
    # Test        : NAME-4016
    # Description : Check main domain (domain <domain name> in /etc/resolv.conf)
    Register --test-no NAME-4016 --weight L --network NO --description "" #Check /etc/resolv.conf default domain"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "R-TEC-NAME-4016-Teste: check /etc/resolv.conf for default domain"
	if [ -f /etc/resolv.conf ]; then
	    logtext "R-TEC-NAME-4016-Resultado: /etc/resolv.conf found"
	    FIND=`cat /etc/resolv.conf | grep "^domain" | awk '{ print $2 }'`
	    if [ "${FIND}" = "" ]; then
	        logtext "R-TEC-NAME-4016-Resultado: no default domain found"
		Display --indent 2 --text "" #- R-TEC-NAME-4016-Verificado DNS padrão ..." --result NENHUM --color WHITE
	      else
	        logtext "R-TEC-NAME-4016-Resultado: found default domain"
		logtext "R-TEC-NAME-4016-Saída: ${FIND}"
		report "resolv_conf_domain=${I}"
	      	Display --indent 2 --text "" #- R-TEC-NAME-4016-Verificado DNS padrão ..." --result ENCONTRADO --color GREEN
		RESOLV_DOMAINNAME="${FIND}"
	    fi
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4018
    # Description : Check search domains in /etc/resolv.conf
    # Notes       : Maximum of one search keyword is allowed in /etc/resolv.conf
    Register --test-no NAME-4018 --weight L --network NO --description "" #Check /etc/resolv.conf search domains"
    if [ ${SKIPTEST} -eq 0 ]; then
        N=0
	logtext "R-TEC-NAME-4018-Teste: check /etc/resolv.conf for search domains"
	if [ -f /etc/resolv.conf ]; then
	    logtext "R-TEC-NAME-4018-Resultado: /etc/resolv.conf found"
	    FIND=`cat /etc/resolv.conf | grep "^search" | sed 's/^search //'`
	    if [ "${FIND}" = "" ]; then
	        logtext "R-TEC-NAME-4018-Resultado: no search domains found, default domain is being used"
	      else
		for I in ${FIND}; do
		    logtext "R-TEC-NAME-4018-Found search domain: ${I}"
		    report "resolv_conf_search_domain[]=${I}"
		    N=`expr ${N} + 1`
	        done
		# Warn if we have more than 6 search domains, which is maximum in most resolvers
		if [ ${N} -gt 6 ]; then
		    logtext "R-TEC-NAME-4018-Resultado: Found ${N} search domains"
		    Display --indent 2 --text "" #- R-TEC-NAME-4018-Verificado search domains..." --result NAO OK --color YELLOW
		    ReportWarning ${TEST_NO} "" #L" "R-TEC-NAME-4018-Found more than 6 search domains, which is usually more than the maximum allowed number in most resolvers"
		  else
		    logtext "R-TEC-NAME-4018-Resultado: Found ${N} search domains"
		    Display --indent 2 --text "" #- R-TEC-NAME-4018-Verificado search domains..." --result ENCONTRADO --color GREEN
		fi
	    fi
	  else
	    logtext "R-TEC-NAME-4018-Resultado: /etc/resolv.conf does not exist, skipping test"
	    Display --indent 2 --text "" #- R-TEC-NAME-4018-Verificado search domains..." --result "NAO OK" --color YELLOW
	fi

	# Check amount of search domains (max 1)
	    FIND=`cat /etc/resolv.conf | grep "^search" | wc -l | tr -s ' ' | tr -d ' '`
	    if [ ! "${FIND}" = "0" -a ! "${FIND}" = "1" ]; then
	        logtext "R-TEC-NAME-4018-Resultado: found ${FIND} line(s) with a search statement (expecting less than 2 lines)"    
		Display --indent 4 --text "" #- R-TEC-NAME-4018-Verificado search domains lines..." --result "CONFIG ERROR" --color YELLOW
		ReportWarning ${TEST_NO} "" #L" "R-TEC-NAME-4018-Found more than 1 search lines in /etc/resolv.conf, which is probably a misconfiguration"
	      else
	        logtext "R-TEC-NAME-4018-Resultado: found ${FIND} line(s) with a search statement (expecting less than 2 lines)"
	    fi
    fi
#
#################################################################################
#
    # Test        : NAME-4020
    # Description : Check non default resolv.conf options
    Register --test-no NAME-4020 --weight L --network NO --description "" #Check non default options"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "R-TEC-NAME-4020-Teste: check /etc/resolv.conf for non default options"
	if [ -f /etc/resolv.conf ]; then
	    logtext "R-TEC-NAME-4020-Resultado: /etc/resolv.conf found"
	    FIND=`grep "^options" /etc/resolv.conf | awk '{ print $2 }'`
	    if [ "${FIND}" = "" ]; then
		logtext "R-TEC-NAME-4020-Resultado: no specific other options configured in /etc/resolv.conf"
	        Display --indent 2 --text "" #- R-TEC-NAME-4020-Verificado /etc/resolv.conf options..." --result "NENHUM" --color WHITE
              else
	        for I in ${FIND}; do
	            logtext "R-TEC-NAME-4020-Found option: ${I}"
		    report "resolv_conf_option[]=${I}"
	    	    #rotate --> add performance tune point
	    	    #timeout <3 --> add performe tune point
	        done
	        Display --indent 2 --text "" #- R-TEC-NAME-4020-Verificado /etc/resolv.conf options..." --result "OK" --color GREEN
	    fi
	  else
	    logtext "R-TEC-NAME-4020-Resultado: /etc/resolv.conf not found, test skipped"
	    Display --indent 2 --text "" #- R-TEC-NAME-4020-Verificado /etc/resolv.conf options..." --result "NAO OK" --color YELLOW
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4024
    # Description : Check Solaris uname -n output
    Register --test-no NAME-4024 --os Solaris --weight L --network NO --description "" #Solaris uname -n output"
    if [ ${SKIPTEST} -eq 0 ]; then
	FIND=`uname -n`
	logtext "R-TEC-NAME-4024-Resultado: 'uname -n' returned ${FIND}"
        Display --indent 2 --text "" #- R-TEC-NAME-4024-Verificado uname -n output..." --result PRONTO --color GREEN
    fi
#
#################################################################################
#
    # Test        : NAME-4026
    # Description : Check Solaris /etc/nodename
    # Notes       : If a system is standalone, /etc/nodename should contain a system name only, not FQDN
    Register --test-no NAME-4026 --os Solaris --weight L --network NO --description "" #Check /etc/nodename"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "R-TEC-NAME-4026-Teste: Verificado /etc/nodename"
	if [ -f /etc/nodename ]; then
	    logtext "R-TEC-NAME-4026-Resultado: file /etc/nodename exists"
	    FIND=`cat /etc/nodename`
	    logtext "R-TEC-NAME-4026-Saída: ${FIND}"
	    Display --indent 2 --text "" #- R-TEC-NAME-4026-Verificado /etc/nodename..." --result "PRONTO" --color GREEN
	  else
	    logtext "R-TEC-NAME-4026-Resultado: file /etc/nodename could not be found"
            Display --indent 2 --text "" #- R-TEC-NAME-4026-Verificado /etc/nodename..." --result "NAO OK" --color YELLOW
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4028
    # Description : Check DNS domain name
    # To Do       : grep ^DOMAINNAME /etc/conf.d/domainname (remove "'s)
    Register --test-no NAME-4028 --weight L --network NO --description "" #Check domain name"
    if [ ${SKIPTEST} -eq 0 ]; then
	DOMAINNAME=""
	logtext "R-TEC-NAME-4028-Teste: Verificado file /etc/domainname"
        if [ -f /etc/domainname ]; then
	    logtext "R-TEC-NAME-4028-Resultado: file /etc/domainname exists"
	    FIND2=`cat /etc/domainname`
	    if [ ! "${FIND}" = "" ]; then
	        logtext "R-TEC-NAME-4028-Found domain name: ${FIND}"
		DOMAINNAME="${FIND}"
	      else
	        logtext "R-TEC-NAME-4028-Resultado: no domain name found in file"
	    fi
	  else
	    logtext "R-TEC-NAME-4028-Resultado: file /etc/domainname does not exist"
	fi
	
	logtext "R-TEC-NAME-4028-Teste: Verificado if dnsdomainname command is available"
	if [ ! "${DNSDOMAINNAMEBINARY}" = "" ]; then
	    FIND2=`${DNSDOMAINNAMEBINARY} 2> /dev/null`
	    if [ ! "${FIND2}" = "" ]; then
	        logtext "R-TEC-NAME-4028-Resultado: dnsdomainname command returned a value"
		logtext "R-TEC-NAME-4028-Found domain name: ${FIND2}"
		DOMAINNAME="${FIND2}"
	      else
	        logtext "R-TEC-NAME-4028-Resultado: dnsdomainname command returned no value"
	    fi
	  else
	    logtext "R-TEC-NAME-4028-Resultado: dnsdomainname binary not found, skip specific test"
	fi
	
	# If files and commands can't be found, use defined value from resolv.conf
        if [ "${DOMAINNAME}" = "" ]; then
	    if [ ! "${RESOLV_DOMAINNAME}" = "" ]; then
	        logtext "R-TEC-NAME-4028-Resultado: using domain name from /etc/resolv.conf"
	    fi
	fi
	    
	if [ ! "${DOMAINNAME}" = "" ]; then
	    logtext "R-TEC-NAME-4028-Resultado: found domain name"
	    report "R-TEC-NAME-4028-domainname=${DOMAINNAME}"
            Display --indent 2 --text "" #- R-TEC-NAME-4028-Searching DNS domain name..." --result "OK" --color GREEN
	    Display --indent 6 --text "" #R-TEC-NAME-4028-Domain name: ${DOMAINNAME}"
	  else
            Display --indent 2 --text "" #- R-TEC-NAME-4028-Searching DNS domain name..." --result "DESCONHECIDO" --color YELLOW	
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4032
    # Description : Check name service caching daemon (NSCD) status
    Register --test-no NAME-4032 --weight L --network NO --description "" #Check nscd status"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "R-TEC-NAME-4032-Teste: Verificado nscd status"
	FIND=`${PSBINARY} ax | grep "nscd" | grep -v "nscd"`
	if [ ! "${FIND}" = "" ]; then
	    logtext "R-TEC-NAME-4032-Resultado: nscd is running"
            Display --indent 2 --text "" #- R-TEC-NAME-4032-Verificado nscd status..." --result OK --color GREEN	    
	  else 
	    logtext "R-TEC-NAME-4032-Resultado: nscd is not running"
            Display --indent 2 --text "" #- R-TEC-NAME-4032-Verificado nscd status..." --result "NAO OK" --color WHITE
	    #YYY show performance suggestion if LDAP is used
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4202
    # Description : Check if BIND is running
    Register --test-no NAME-4202 --weight L --network NO --description "" #Check BIND status"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "R-TEC-NAME-4202-Teste: Verificado for running BIND instance"
	FIND=`${PSBINARY} ax | grep "/named" | grep -v "grep"`
	if [ ! "${FIND}" = "" ]; then
	    logtext "R-TEC-NAME-4202-Resultado: found BIND process"
	    Display --indent 2 --text "" #- R-TEC-NAME-4202-Verificado BIND status..." --result "OK" --color GREEN
	    BIND_RUNNING=1
	  else
	    logtext "R-TEC-NAME-4202-Resultado: BIND not running"
	    Display --indent 2 --text "" #- R-TEC-NAME-4202-Verificado BIND status..." --result "NAO OK" --color WHITE
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4204
    # Description : Check configuration file of BIND
    if [ ${BIND_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4204 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Search BIND configuration file"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "R-TEC-NAME-4204-Teste: Search BIND configuration file"
	#YYY add chrooted environments
	for I in ${BIND_CONFIG_LOCS}; do
	    if [ -f ${I}/named.conf ]; then
	        BIND_CONFIG_LOCATION="${I}/named.conf"
	        logtext "R-TEC-NAME-4204-Resultado: found configuration file (${BIND_CONFIG_LOCATION})"		
	    fi
	done
	if [ ! "${BIND_CONFIG_LOCATION}" = "" ]; then
	    Display --indent 4 --text "" #- R-TEC-NAME-4204-Verificado BIND configuration file..." --result "OK" --color GREEN
	  else
	    Display --indent 4 --text "" #- R-TEC-NAME-4204-Verificado BIND configuration file..." --result "NAO OK" --color YELLOW
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4206
    # Description : Check BIND configuration file consistency
    if [ ${BIND_RUNNING} -eq 1 -a ! "${BIND_CONFIG_LOCATION}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4206 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Check BIND configuration consistency"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "R-TEC-NAME-4206-Teste: searching for named-checkconf binary"
        if [ ! "${NAMEDCHECKCONFBINARY}" = "" ]; then
	    logtext "R-TEC-NAME-4206-Resultado: named-checkconf is installed"
	    FIND=`${NAMEDCHECKCONFBINARY} ${BIND_CONFIG_LOCATION}; echo $?`
	    if [ "${FIND}" = "0" ]; then
	        logtext "R-TEC-NAME-4206-Resultado: configuration file ${BIND_CONFIG_LOCATION} seems to be fine"
	        Display --indent 4 --text "" #- R-TEC-NAME-4206-Verificado BIND configuration consistency..." --result "OK" --color GREEN
	      else
	        logtext "R-TEC-NAME-4206-Resultado: possible errors found in ${BIND_CONFIG_LOCATION}"
	        Display --indent 4 --text "" #- R-TEC-NAME-4206-Verificado BIND configuration consistency..." --result NAO OK --color RED
		#YYY warning
	    fi
	  else
	    logtext "R-TEC-NAME-4206-Resultado: named-checkconf not found, skipping test"
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4208
    # Description : Check DNS server type (master, slave, caching, forwarding)
    #Register --test-no NAME-4050 --weight L --network NO --description "" #Check nscd status"
    #if [ ${SKIPTEST} -eq 0 ]; then
#
#################################################################################
#
    # Test        : NAME-4210
    # Description : Check if we can determine useful information from banner
    if [ ${BIND_RUNNING} -eq 1 -a ! "${BIND_CONFIG_LOCATION}" = "" -a ! "${DIGBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4210 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Check DNS banner"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "R-TEC-NAME-4210-Teste: Trying to determine version from banner"
	FIND=`${DIGBINARY} @localhost version.bind chaos txt | grep "^version.bind" | grep TXT | egrep "[0-9].[0-9].[0-9]*"`
	if [ "${FIND}" = "" ]; then
	    logtext "R-TEC-NAME-4210-Resultado: no useful information in banner found"
	    Display --indent 4 --text "" #- R-TEC-NAME-4210-Verificado BIND version in banner ..." --result "OK" --color GREEN
	    AddHP 2 2
	  else
	    logtext "R-TEC-NAME-4210-Resultado: possible BIND version available in version banner"
	    Display --indent 4 --text "" #- R-TEC-NAME-4210-Verificado BIND version in banner..." --result NAO OK --color RED
	    ReportWarning ${TEST_NO} "" #M" "R-TEC-NAME-4210-Found BIND version in banner"
	    #YYY suggestion
	    AddHP 0 2
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4212
    # Description : Check version option in BIND configuration
    #if [ ${BIND_RUNNING} -eq 1 -a ! "${BIND_CONFIG_LOCATION}" = "" -a ! "${DIGBINARY}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    #Register --test-no NAME-4210 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Check DNS banner"
#
#################################################################################
#
    # Test        : NAME-4220
    # Description : Check if we can perform a zone transfer of primary domain
    #Register --test-no NAME-4220 --weight L --network NO --description "" #Check zone transfer"
    #if [ ${SKIPTEST} -eq 0 ]; then
#
#################################################################################
#
    # Test        : NAME-4222
    # Description : Check if we can perform a zone transfer of PTR (of primary domain)
    #Register --test-no NAME-4222 --weight L --network NO --description "" #Check zone transfer"
    #if [ ${SKIPTEST} -eq 0 ]; then
#
#################################################################################
#
    # Test        : NAME-4230
    # Description : Check if PowerDNS is running
    Register --test-no NAME-4230 --weight L --network NO --description "" #Check PowerDNS status"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "R-TEC-NAME-4230-Teste: Verificado for running PowerDNS instance"
	FIND=`${PSBINARY} ax | grep "/pdns_server" | grep -v "grep"`
	if [ ! "${FIND}" = "" ]; then
	    logtext "R-TEC-NAME-4230-Resultado: found PowerDNS process"
	    Display --indent 2 --text "" #- R-TEC-NAME-4230-Verificado PowerDNS status..." --result "OK" --color GREEN
	    POWERDNS_RUNNING=1
	  else
	    logtext "R-TEC-NAME-4230-Resultado: PowerDNS not running"
	    Display --indent 2 --text "" #- R-TEC-NAME-4230-Verificado PowerDNS status..." --result "NAO OK" --color WHITE
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4232
    # Description : Check PowerDNS configuration file
    if [ ${POWERDNS_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4232 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Search PowerDNS configuration file"
    if [ ${SKIPTEST} -eq 0 ]; then
	logtext "R-TEC-NAME-4232-Teste: Search PowerDNS configuration file"
	#YYY add chrooted environments
	for I in ${POWERDNS_CONFIG_LOCS}; do
	    if [ -f ${I}/pdns.conf ]; then
	        POWERDNS_CONFIG_LOCATION="${I}/pdns.conf"
	        logtext "R-TEC-NAME-4232-Resultado: found configuration file (${POWERDNS_CONFIG_LOCATION})"		
	    fi
	done
	if [ ! "${POWERDNS_CONFIG_LOCATION}" = "" ]; then
	    Display --indent 4 --text "" #- R-TEC-NAME-4232-Verificado PowerDNS configuration file..." --result "OK" --color GREEN
	  else
	    Display --indent 4 --text "" #- R-TEC-NAME-4232-Verificado PowerDNS configuration file..." --result "NAO OK" --color YELLOW
	fi
    fi
#
#################################################################################
#
#    # Test        : NAME-4234
#    # Description : Check PowerDNS configuration file consistency
#    if [ ${POWERDNS_RUNNING} -eq 1 -a ! "${POWERDNS_CONFIG_LOCATION}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
#    Register --test-no NAME-4234 --weight L --network NO --description "" #Check PowerDNS configuration consistency"
#    if [ ${SKIPTEST} -eq 0 ]; then
#    fi
#
#################################################################################
#
    # Test        : NAME-4236
    # Description : Check PowerDNS backends
    if [ ${POWERDNS_RUNNING} -eq 1 -a ! "${POWERDNS_CONFIG_LOCATION}" = "" ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4236 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Check PowerDNS backends"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "R-TEC-NAME-4236-Teste: Verificado for PowerDNS backends"
	FIND=`cat ${POWERDNS_CONFIG_LOCATION} | grep "^launch" | awk -F= '{ print $2 }'`
	if [ ! "${FIND}" = "" ]; then
	    for I in ${FIND}; do
	        logtext "R-TEC-NAME-4236-Found backend: ${I}"
	    done
	    Display --indent 4 --text "" #- R-TEC-NAME-4236-Verificado PowerDNS backends..." --result "OK" --color GREEN
	  else
	    logtext "R-TEC-NAME-4236-Resultado: no PowerDNS backends found"
	    Display --indent 4 --text "" #- R-TEC-NAME-4236-Verificado PowerDNS backends..." --result "NAO OK" --color YELLOW
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4302
    # Description : Check NIS ypbind daemon status
    Register --test-no NAME-4304 --weight L --network NO --description "" #Check NIS ypbind status"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "R-TEC-NAME-4302-Teste: Verificado status of ypbind daemon"
	FIND=`${PSBINARY} ax | grep "ypbind" | grep -v "grep"`
	if [ ! "${FIND}" = "" ]; then
	    logtext "R-TEC-NAME-4302-Resultado: ypbind is running"
	    Display --indent 2 --text "" #- R-TEC-NAME-4302-Verificado ypbind status..." --result "OK" --color GREEN
	    YPBIND_RUNNING=1
	  else
	    logtext "R-TEC-NAME-4302-Resultado: ypbind is not active"
	    Display --indent 2 --text "" #- R-TEC-NAME-4302-Verificado ypbind status..." --result "NAO OK" --color WHITE
	fi
    fi
#
#################################################################################
#
    # Test        : NAME-4306
    # Description : Check NIS domain
    # Notes       : FreeBSD: sysctl kern.domainname
    if [ ${YPBIND_RUNNING} -eq 1 ]; then PREQS_MET="YES"; else PREQS_MET="NO"; fi
    Register --test-no NAME-4306 --preqs-met ${PREQS_MET} --weight L --network NO --description "" #Check NIS domain"
    if [ ${SKIPTEST} -eq 0 ]; then
        logtext "R-TEC-NAME-4306-Teste: Verificado `domainname` for NIS domain value"
	FIND=`${DOMAINNAMEBINARY} | grep -v "(none)"`
	if [ ! "${FIND}" = "" ]; then
	    logtext "Value: ${FIND}"
	    NISDOMAIN="${FIND}"
	  else
	    logtext "R-TEC-NAME-4306-Resultado: no NIS domain found in command output"
	fi
	# Solaris / Linux style
	logtext "R-TEC-NAME-4306-Teste: Verificado file /etc/defaultdomain"
	if [ -f /etc/defaultdomain ]; then
	    logtext "R-TEC-NAME-4306-Resultado: file /etc/defaultdomain exists"
	    FIND2=`cat /etc/defaultdomain`
	    if [ ! "${FIND2}" = "" ]; then
	        logtext "R-TEC-NAME-4306-Saída: ${FIND2}"
		NISDOMAIN="${FIND2}"
	      else
	        logtext "R-TEC-NAME-4306-Resultado: no NIS domain found in file"
	    fi
	fi
	# Red Hat style
	logtext "R-TEC-NAME-4306-Teste: Verificado /etc/sysconfig/network"
	if [ -f /etc/sysconfig/network ]; then
	    logtext "R-TEC-NAME-4306-Resultado: file /etc/sysconfig/network exists"
	    logtext "R-TEC-NAME-4306-Teste: Verificado NISDOMAIN value in file"
	    FIND3=`grep "^NISDOMAIN" /etc/sysconfig/network | awk -F= '{ print $2 }' | sed 's/"//g'`
	    if [ ! "${FIND3}" = "" ]; then
	        logtext "R-TEC-NAME-4306-Found NIS domain: ${FIND3}"
		NISDOMAIN="${FIND3}"
	      else
	        logtext "R-TEC-NAME-4306-Resultado: No NIS domain found in file"
	    fi
	  else
	    logtext "R-TEC-NAME-4306-Resultado: file /etc/sysconfig/network does not exist"
	fi
	# Check if we found any NIS domain
	if [ ! "${NISDOMAIN}" = "" ]; then    
	    logtext "R-TEC-NAME-4306-Found NIS domain: ${NISDOMAIN}"
	    report "nisdomain=${NISDOMAIN}"
	    Display --indent 4 --text "" #- R-TEC-NAME-4306-Verificado NIS domain..." --result "OK" --color GREEN
	  else
	    logtext "R-TEC-NAME-4306-Resultado: No NIS domain found"
	    Display --indent 4 --text "" #- R-TEC-NAME-4306-Verificado NIS domain..." --result "DESCONHECIDO" --color YELLOW
	fi
    fi
#
#################################################################################
#

wait_for_keypress

#
#================================================================================
# hardeningone - Copyleft GPL3 2010-2011, Mauro Risonho de Paula Assumpção -  - 
