#!/bin/sh

#################################################################################
#
#   hardeningone
# ------------------
#
# Copyleft GPL3 2010-2011, Mauro Risonho de Paula Assumpcao (mauro.risonho@gmail.com), 
# Web site: http://
#
# This software is licensed under GPL, version 3. See LICENSE file for
# usage of this software.
#
#################################################################################
#
# Consts
#
#################################################################################
#

# Program information

# Paths where system and program binaries are located
# Includes Sun Solaris dirs
BINPATHS="/bin /sbin /usr/bin /usr/sbin /usr/local/bin /usr/local/sbin \
          /usr/local/libexec /usr/libexec /usr/sfw/bin /usr/sfw/sbin \
	  /usr/sfw/libexec /opt/sfw/bin /opt/sfw/sbin /opt/sfw/libexec \
	  /usr/xpg4/bin /usr/css/bin /usr/ucb"

#
#################################################################################
#
# Deprecated
#
#################################################################################
#
    HOME_HISTORY_AUDIT_TITLE="Tipo de Arquivo de Histórico Incorreto"
    HOME_HISTORY_AUDIT_DESCRIPTION=""

    HOME_HISTORY_LOG_TITLE="Verificar o Histórico do tipo de arquivos"
    HOME_HISTORY_LOG_DESCRIPTION="Verificar o Histórico do tipo de arquivos"
    HOME_HISTORY_LOG_TEXT="Arquivos de Histórico, sao normalmente de 'arquivo' do tipo. Symbolic links and other types can be riskful"
    
    HOME_PATH_LOG_MESSAGE="A single dot in the PATH variable of a user can be a risk, while executing commands in for example a home directory."
    
    USER_PASSWD_DOUBLEUID_AUDIT_TITLE="Non unique UIDs"
    USER_PASSWD_DOUBLEUID_AUDIT_DESCRIPTION="Non unique UIDs in passwd file"
    USER_PASSWD_DOUBLEUID_AUDIT_TEXT="Non unique UIDs can riskful for the system or part of a configuration mistake"
    
    KERNEL_ACTIVE_MODULES_TITLE="Active kernel modules (KLDs)"
    KERNEL_ACTIVE_MODULES_DESCRIPTION="View all active kernel modules (including kernel)"
    KERNEL_ACTIVE_MODULES_TEXT="Displays the loaded kernel modules in memory. Make sure to check the integrity of the kld tools."
#
#################################################################################
#
# Initialize defaults
#
#################################################################################
#
# == Variable initializing ==
#
    AUDITORNAME=""
    PROFILE=""
    REPORTFILE=""
    AFICKBINARY=""
    AIDEBINARY=""
    AASTATUSBINARY=""
    CHKROOTKITBINARY=""
    CHKCONFIGBINARY=""
    FILEVALUE=""
    FIND=""
    GRPCKBINARY=""
    IPTABLESBINARY=""
    LINUX_VERSION=""
    LOGFILE=""
    OS=""; OS_MODE=""
    OSIRISBINARY=""
    PIDFILE=""
    PROFILEVALUE=""
    RKHUNTERBINARY=""
    RPMBINARY=""
    SAMHAINBINARY=""
    SCAN_TEST_HEAVY=""; SCAN_TEST_MEDIUM=""; SCAN_TEST_LOW=""
    SESTATUSBINARY=""
    SYSLOGNGBINARY=""
    TEST_SKIP_ALWAYS=""
    TRIPWIREBINARY=""
    VALUE=""
#
#################################################################################
#
# == Options ==
#
#   Option			  Description
# --------------------------------------------------------------------------
    CRONJOB=0			# Run as a cronjob
    CTESTS_PERFORMED=0		# Number of tests which are performed
    HPPOINTS=0                  # Number of hardening points
    HPTOTAL=0                   # Maximum number of hardening points
    LOG_INCORRECT_OS=1		# Log tests with incorrect OS
    NEVERBREAK=0		# Don't wait for user input
    QUICKMODE=0			# Don't wait for user input
    QUIET=0			# Show normal messages and warnings as well
    SKIPLOGTEST=0		# Skip logging for one test
    SKIP_UPGRADE_TEST=0		# Skip upgrade test
    TESTS_TO_PERFORM=""		# Which tests only to perform
    TEST_PAUSE_TIME=0		# Default pause time
    TOTAL_TESTS=0		# Total amount of tests (counter)
    VIEWHELP=0			# Show help
    VIEWUPDATEINFO=0		# View program/database version
    WRONGOPTION=0		# A wrong option is used
#
#################################################################################
#
    # Packages
    PKG_COMPILER_INSTALLED=0
#
#################################################################################
#
# Colors
#
#################################################################################
#
#   Color name			  Description
# --------------------------------------------------------------------------
    NORMAL="[0;39m" 
    WARNING="[1;31m"		# Bad (red)
    SECTION="[1;33m"		# Section (yellow)
    NOTICE="[1;33m"		# Notice (yellow)
    OK="[1;32m"		# Ok (green)
    BAD="[1;31m"		# Bad (red)

    # Real color names
    YELLOW="[1;33m"		# Yellow
    WHITE="[1;37m"		# White
    GREEN="[1;32m"		# Green
    RED="[1;31m"		# Red
#
#################################################################################
#

#================================================================================
# hardeningone - Copyleft GPL3 2010-2011, Mauro Risonho de Paula Assumpcao -  - 
